var hero = {
    name:"Me",
    uid: "hero",
    level:0,
    type:"Undead Knight",
    accuracy: 65,
    accuracySaved: 65,
    dodge: 10,
    dodgeSaved: 10,
    armor: 1,
    armorSaved: 1,
    weapon: ['Bone Scabre', 8, 12],
    weaponSaved: [ "", 8, 12],
    skillPointsCurrent:6,
    skillPoints:6,
    hitPointsCurrent:35,
    hitPoints:35,
    skills:['Keen eye','Enrage','Spit in their eye!'],
    ui_id: "#hero-ui",
    healthpotion: 2,
    skillspotion: 2,
};

var zombieBob = {
    name:"Farmer Bob Brains",
    uid: "zombieBob",
    level:1,
    type:"Zombie Botanist",
    accuracy: 60,
    dodge: 15,
    armor: 0,
    weapon: ['Pitch Fork', 5, 10],
    skillPointsCurrent:10,
    skillPoints:10,
    hitPointsCurrent:18,
    hitPoints:18,
    skills:['Bite','Skewer!'],
    ui_id: "#enemy-ui-one",
    img_id: "#zombieBob",
    img: function(){$("#enemy-ui-one").append('<img id="'+currentEnemies[0].uid+'" class="enemies" src="images/zombie-farmer.png">');},
};

var mountainGiant = {
    name:"Mountain Giant",
    uid: "mountainGiant",
    level:6,
    type:"Rocking and Rolling",
    accuracy: 50,
    dodge: 5,
    armor: 6,
    weapon: ['Fists', 18, 20],
    skillPointsCurrent:4,
    skillPoints:4,
    hitPointsCurrent:90,
    hitPoints:90,
    skills:['Crush','Pound'],
    ui_id: "#enemy-ui-one",
    img_id: "#mountainGiant",
    img: function(){$("#enemy-ui-one").append('<img id="'+currentEnemies[0].uid+'" class="enemies" src="images/rock-monster.png">');},
};

var ogre = {
    name:"Mogor",
    uid: "ogre",
    level:3,
    type:"Crush, kill, than eat",
    accuracy: 65,
    dodge: 22,
    armor: 2,
    weapon: ['Club', 9, 14],
    skillPointsCurrent:4,
    skillPoints:4,
    hitPointsCurrent:28,
    hitPoints:28,
    skills:['Keel!','Destoyah!'],
    ui_id: "#enemy-ui-one",
    img_id: "#ogre",
    img: function(){$("#enemy-ui-one").append('<img id="'+currentEnemies[0].uid+'" class="enemies" src="images/ogre.png">');},
};

var viking = {
    name:"Bjørn the Bear",
    uid: "viking",
    level:3,
    type:"Loves to raid, raids to love",
    accuracy: 70,
    dodge: 15,
    armor: 2,
    weapon: ['My Big Friend', 10, 16],
    skillPointsCurrent:4,
    skillPoints:4,
    hitPointsCurrent:45,
    hitPoints:45,
    skills:[],
    ui_id: "#enemy-ui-one",
    img_id: "#viking",
    img: function(){$("#enemy-ui-one").append('<img id="'+currentEnemies[0].uid+'" class="enemies" src="images/viking.png">');},
};

var dungeonGuard = {
    name:"Butcher Brute",
    uid: "dungeonGuard",
    level:5,
    type:"First you peel them, then you eat them.",
    accuracy: 75,
    dodge: 20,
    armor: 3,
    weapon: ['Meat Cleaver', 20, 25],
    skillPointsCurrent:4,
    skillPoints:4,
    hitPointsCurrent:50,
    hitPoints:50,
    skills:['Peel','Carve'],
    ui_id: "#enemy-ui-one",
    img_id: "#dungeonGuard",
    img: function(){$("#enemy-ui-one").append('<img id="'+currentEnemies[0].uid+'" class="enemies" src="images/dungeon-guard.png">');},
};

var berserker = {
    name:"Imperial Berserker",
    uid: "berserker",
    level:4,
    type:"Heads will roll.",
    accuracy: 85,
    dodge: 25,
    armor: 0,
    weapon: ['Executioners Axe', 5, 30],
    skillPointsCurrent:4,
    skillPoints:4,
    hitPointsCurrent:35,
    hitPoints:35,
    skills:['Chop','Raging'],
    ui_id: "#enemy-ui-one",
    img_id: "#berserker",
    img: function(){$("#enemy-ui-one").append('<img id="'+currentEnemies[0].uid+'" class="enemies" src="images/berserker.png">');},
};

var castleGuard = {
    name:"Castle Guard",
    uid: "castleGuard",
    level:7,
    type:"None shall pass",
    accuracy: 80,
    dodge: 35,
    armor: 4,
    weapon: ['Ginsu Axe', 20, 30],
    skillPointsCurrent:4,
    skillPoints:4,
    hitPointsCurrent:55,
    hitPoints:55,
    skills:['Violent Strike','Face-off'],
    ui_id: "#enemy-ui-one",
    img_id: "#castleGuard",
    img: function(){$("#enemy-ui-one").append('<img id="'+currentEnemies[0].uid+'" class="enemies" src="images/castle-guard.png">');},
};

var metalOgre = {
    name:"Metal Ogre",
    uid: "metalOgre",
    level:10,
    type:"Personal body guard of the king",
    accuracy: 70,
    dodge: 20,
    armor: 6,
    weapon: ['Big Axe', 20, 40],
    skillPointsCurrent:4,
    skillPoints:4,
    hitPointsCurrent:65,
    hitPoints:65,
    skills:['Violent Strike','Face-off'],
    ui_id: "#enemy-ui-one",
    img_id: "#metalOgre",
    img: function(){$("#enemy-ui-one").append('<img id="'+currentEnemies[0].uid+'" class="enemies" src="images/metal-ogre.png">');},
};

var dragon = {
    name:"Deathbringer",
    uid: "dragon",
    level:99,
    type:"Peon crusher",
    accuracy: 90,
    dodge: 30,
    armor: 8,
    weapon: ['Dragon Claws', 35, 45],
    skillPointsCurrent:4,
    skillPoints:4,
    hitPointsCurrent:120,
    hitPoints:120,
    skills:['Bite Head Off','Fire Breath'],
    ui_id: "#enemy-ui-one",
    img_id: "#dragon",
    img: function(){$("#enemy-ui-one").append('<img id="'+currentEnemies[0].uid+'" class="enemies flying-in-place" src="images/dragon.png">');},
};

var theking = {
    name:"King Vlad the Inhaler",
    uid: "theking",
    level:25,
    type:"Supreme Ruler & Overall Good Guy",
    accuracy: 85,
    dodge: 45,
    armor: 5,
    weapon: ['Lights Edge', 30, 35],
    skillPointsCurrent:10,
    skillPoints:10,
    hitPointsCurrent:60,
    hitPoints:60,
    skills:['Cleave','Accurate Strike'],
    ui_id: "#enemy-ui-one",
    img_id: "#theking",
    img: function(){$("#enemy-ui-one").append('<img id="'+currentEnemies[0].uid+'" class="enemies" src="images/theking.png">');},
};
